FROM tomcat
MAINTAINER @mmaha

RUN apt-get update && apt-get -y install \
	git \
	openjdk-7-jdk \
	maven

RUN git clone https://github.com/spring-projects/spring-security-saml.git 

# Setup admin user in case we want to administer tomcat
COPY tomcat-users.xml /usr/local/tomcat/conf/

WORKDIR spring-security-saml/sample

# idp.xml needs to be generated by running the get-metadata.sh script
COPY idp.xml src/main/resources/metadata

RUN ../gradlew build install

RUN mv build/libs/spring-security-saml2-sample.war /usr/local/tomcat/webapps/

EXPOSE  8080
